modLoader="javafml"
loaderVersion="[43,)"
license='MIT'

[[mods]]
modId="tgbridge"
version="${version}"
displayName="Telegram Bridge"
authors="vanutp"
description="Sync your game with Telegram"
logoFile="icon.png"
displayURL="https://github.com/vanutp/tgbridge"
displayTest="IGNORE_ALL_VERSION"
[[dependencies.tgbridge]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tgbridge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
